// import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './../globals.css'

const dm = DM_Sans({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Phase-r',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dm.className}`}>
        {children}
      </body>
    </html>
  )
}
