// import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './../globals.css'
import Navbar from './Navbar'
import Footer from './Footer'
import Sidebar from './Sidebar'

const dm = DM_Sans({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Phase-r',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/landing_page/Logo.svg" sizes="any" />
      <body className={`${dm.className}`}>
        <Navbar />
        <div className='hidden lg:block xl:block'>
          {/* <Sidebar /> */}
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
